Home work 2
Genesis-Front-End-School/clean-code-principes-Markusplay pull request #3
Opened 2023-04-26 19:20 UTC by Markusplay

Homework 2 by Shylo Mykhailo
Telegram: @MarkusdeUa

2023-04-27 18:40 UTC, v4voloshyn requested changes
Need small issues fix

2023-04-27 18:40 UTC, v4voloshyn commented on src/components/common/ui/CourseCard/CourseCard.tsx
> +        <Button
For accessibility rules, all links that redirect to another page (even if it's SPA) should be links, but not buttons. I found [this video](https://youtu.be/ssJsjGZE2sc?t=957) special for you with the right timecode :) I highly recommend watching the whole video!

2023-04-27 18:40 UTC, v4voloshyn commented on src/pages/course-page/CoursePage.tsx
> +      if (
Maybe these  `if` statements should be util functions like `changePlaybackRate` that accept `event` and `videoRef` as props and do some logic?

2023-04-28 09:35 UTC, v4voloshyn commented on src/components/common/ui/CoursePerPage/CoursesPerPage.tsx
> +          videoPreviewLink={course.meta.courseVideoPreview?.link}
I think that all this things that came from `course` you cat put in `CourseCard` as it is `courseData={course}` and then just make destructuring directly in CourseCard `const {id, title, ...} = courseData`. And your `CourseCardProps` interface might be like this: `interface CourseCardProps {
courseData: Course
}` You already have `Course` type in your `types` file in the redux store folder

2023-04-30 10:27 UTC, artemsukach commented on src/components/common/ui/CoursePerPage/CoursesPerPage.tsx
> +      {courses.slice(visitedPages, visitedPages + coursesLimit).map(course => (
|my opinion|
Винести в окрему функцію для кращої читабельності.
Якщо не згоден просто постав реакцію щоб я знав, що можна апрувнути, так як в цілому все добре і це зауваження не критичне

2023-04-30 14:15 UTC, v4voloshyn approved these changes

2023-04-30 16:11 UTC, artemsukach approved these changes

2023-05-03 19:36 UTC, vlad-khozhai approved these changes

2023-05-03 19:36 UTC, vlad-khozhai commented on src/components/common/ui/ListLessons/ListLessons.tsx
> +import React, { Dispatch, FC, SetStateAction } from 'react';
кажется в нексте не нужно импортить React

2023-05-03 19:36 UTC, vlad-khozhai commented on src/pages/course-page/CoursePage.tsx
>    };
Эту функцию можно вынести за пределы компоненты

2023-05-03 19:36 UTC, vlad-khozhai commented on src/pages/main-page/MainPage.tsx
> +    return (pageNumber - 1) * Courses_Per_Page_Limit;
Как правило название таких констант прописаны апперкейсом COURSES_PER_P...

2023-05-06 17:42 UTC, merged