HW 3
Genesis-Front-End-School/clean-code-principes-Markusplay pull request #4
Opened 2023-05-01 18:51 UTC by Markusplay

2023-05-01 19:03 UTC, yulyaolshanska commented on src/components/common/ui/CourseCard/CourseCard.tsx
You can add :void to functions that return nothing

2023-05-01 19:03 UTC, yulyaolshanska commented on src/pages/main-page/MainPage.tsx
>    const [pageNumber, setPageNumber] = useState(1);
add type for useState(1);

2023-05-01 19:10 UTC, yulyaolshanska commented on src/pages/course-page/CoursePage.tsx
>    const router = useRouter();
add type for useRouter();

2023-05-01 19:17 UTC, Markusplay commented on src/components/common/ui/CourseCard/CourseCard.tsx
> You can add :void to functions that return nothing

I have asked our mentor about it. He said that it is not necessary to write `void`.

2023-05-01 19:17 UTC, Markusplay commented on src/components/common/ui/CourseCard/CourseCard.tsx
> > You can add :void to functions that return nothing
> 
> I have asked our mentor about it. He said that it is not really necessary to write `void`.

2023-05-01 19:18 UTC, yulyaolshanska commented on src/components/common/ui/CourseCard/CourseCard.tsx
Ok, i don't now about it

2023-05-01 19:29 UTC, yulyaolshanska approved these changes

2023-05-01 19:31 UTC, v4voloshyn requested changes

2023-05-01 19:31 UTC, v4voloshyn commented on src/pages/course-page/CoursePage.tsx
>    const sortLessons = (lessons: Lesson[] | undefined) => {
Specify returned data

2023-05-01 20:20 UTC, v4voloshyn approved these changes

2023-05-02 22:46 UTC, merged

2023-05-05 15:06 UTC, vlad-khozhai-promova commented on src/components/common/ui/CourseCard/CourseCard.tsx
> +  const [isVideoLinkBroken, setIsVideoLinkBroken] = useState<boolean>(false);
примитивные типы данных не обязательно указывать в useState, в данном примере isVideoLinkBroken примет тип начального значения, которое передается в useState, то есть можно писать просто: 
`const [isVideoLinkBroken, setIsVideoLinkBroken] = useState(false);`

2023-05-05 15:06 UTC, vlad-khozhai-promova commented on src/components/common/ui/CourseCard/CourseCard.tsx
> +  const [isVideoLinkBroken, setIsVideoLinkBroken] = useState<boolean>(false);
но это не обязательно

2023-05-05 15:06 UTC, vlad-khozhai commented on src/components/common/ui/ListLessons/ListLessons.tsx
> +  const seconds: number = duration - minutes * 60;
если duration и minutes были уже определены как number, то seconds можно не определять тип, он по умолчанию примет number

2023-05-05 15:06 UTC, vlad-khozhai-promova commented on src/pages/course-page/CoursePage.tsx
> +  const lessons: Lessons | null = useAppSelector(selectDetails);
если в редаксе все правильно типизировано, то не нужно дополнительно указывать здесь тип, так как useSelector уже вернет типизированное значение

2023-05-05 15:06 UTC, vlad-khozhai commented on src/pages/course-page/CoursePage.tsx
> +  const videoRef = useRef<HTMLVideoElement | null>(null);
здесь писать | null не обязательно

2023-05-05 15:06 UTC, vlad-khozhai commented on src/pages/course-page/CoursePage.tsx
> +  const video: HTMLVideoElement | null = videoRef.current;
video примет тип, который ты указал в рефе, не обязательно дублировать