Hw4 - tests
Genesis-Front-End-School/clean-code-principes-Markusplay pull request #6
Opened 2023-05-08 18:06 UTC by Markusplay

2023-05-10 19:21 UTC, yulyaolshanska commented on src/pages/main-page/MainPage.tsx
> +        (a: any, b: any) =>
any?

2023-05-10 20:02 UTC, yulyaolshanska approved these changes

2023-05-11 22:22 UTC, v4voloshyn requested changes

2023-05-11 22:22 UTC, v4voloshyn commented on package.json
> +    "enzyme": "^3.11.0",
Ця залежність, мабуть також має бути в дев-залежностях

2023-05-11 22:22 UTC, v4voloshyn commented on src/components/common/ui/CourseCard/CourseCard.tsx
> +  const seconds = duration - minutes * 60;
Це можна винести в якусь окрему утиліту яка форматує час по типу MM:SS. В тебе ця функція ще може застосовуватись в `ListLessons.tsx`

2023-05-11 22:22 UTC, v4voloshyn commented on src/components/common/ui/ListLessons/ListLessons.tsx
> +  const seconds = duration - minutes * 60;
Тут може бути функція-утиліта

2023-05-11 22:22 UTC, v4voloshyn commented on src/components/common/ui/ListLessons/ListLessons.tsx
> +          poster={previewImageLink ? previewImageLink : './not-found.png'}
`previewImageLink` можна винести в окрему константу `const poster = previewImageLink || './not-found.png';`

2023-05-11 22:22 UTC, v4voloshyn commented on src/components/common/ui/ListLessons/components/DisabledButton/DisabledButton.test.js
> +    expect(mockHandleClick).not.toHaveBeenCalled();
Мабуть в цьому тесті краще перевірити кноппку на те що вона просто `disabled`. Якщо в неї є цей атрибут, то взаємодіяти з нею ніяк не можна, тому що вона превентить всі івенти. Добавляти в інтерфейс кнопки з атрибутом disabled функцію, яка не трігериться немає сенсу :)

2023-05-11 22:22 UTC, v4voloshyn commented on src/components/common/ui/ListLessons/components/DisabledButton/DisabledButton.tsx
кнопки DIsabled та EnebladeButton краще згрупувати в один компонент Button або просто в одну папку, якщо UI сильно відрізняється, створити там інтерфейс `ListButtonProps`, можливо просто його переіменувати на `ButtonProps` і прокидувати його далі в кнопки.  Кнопки ж не залежать від списку :)

2023-05-11 22:22 UTC, v4voloshyn commented on src/pages/_app.tsx
> +// import '@/styles/globals.scss';
Забув розкоментувати чи видалити? Чи то TODO?

2023-05-11 22:22 UTC, v4voloshyn commented on src/pages/main-page/MainPage.tsx
> +      ) ?? [];
Напрошується функція сортування по типу `import { sortLessons } from '../../utils/sortLessons'`

2023-05-11 22:22 UTC, v4voloshyn commented on src/redux/__tests__/type.test.ts
> +}
Не зовсім розумію для чого ці функції? Прокидується аргумент `a`, повертається аргумент `a`... Що тут тестується або що можна протестувати за їх допомогою?

2023-05-11 22:22 UTC, v4voloshyn commented on src/redux/courses/courseType.test.ts
> +import { testCoursesData } from '../../utils/constants/testData';
teastData це мабуть не константа, а мок. Його мабуть краще винести в папку моків чи щось типу того. Як і всі змінні які є моками, якщо вони дуже громіздкі або не несуть особливого змістовного навантаження

2023-05-11 22:22 UTC, v4voloshyn commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "jest.config.ts", "src/__tests__/useSortLessons.test.ts", "src/pages/404-page/NotFoundPage.test.js", "src/__tests__/404.test.js", "src/__tests__/
Що означає цей інклюд і чому потрібно було вносити всі файли які тестуються в цей список? Якщо це дійсно потрібно, то можна прописати паттерн по типу `**/*.test.{js,ts,tsx}`. І якщо вже юзаєш Тайпскрипт в проекті, то мабуть краще ніяких js розширень. Тримай всі файли в консистентному стані - ts або tsx.

2023-05-15 13:28 UTC, vlad-khozhai approved these changes

2023-05-15 13:28 UTC, vlad-khozhai commented on src/components/common/ui/CourseCard/CourseCard.test.tsx
> +    };
такие данные можно выносить отдельно, так как могут пригодиться в нескольких тестах, и не только в тестах, а например при разработке новой фичи бывает нужно использовать замоканные данные

2023-05-15 13:28 UTC, vlad-khozhai-promova commented on src/components/common/ui/ListLessons/ListLessons.test.tsx
> +  const order = 2;
в некоторых местах ты пропсы выносишь в константы, а в некоторых сразу передаешь в компонент, лучше придерживаться единого стиля

2023-05-15 17:25 UTC, merged

2023-05-16 11:01 UTC, v4voloshyn reviewed
В тебе тут трохи тести посипались. Можна або проставти для зафейлених тестів `test.skip()` щоб потім до них повернутись, або виправити їх. Бо неробочі тести запихати в код то не є гуд. Ми не знатимемо в майбутньому чи в нас щось поламалось чи воно й було поломане з самого початку.
<img width="299" alt="image" src="https://github.com/Genesis-Front-End-School/clean-code-principes-Markusplay/assets/18702961/b843fa40-c3a3-41af-b8f3-436914ff2a5d">

2023-05-16 11:01 UTC, v4voloshyn commented on src/pages/course-page/CoursePage.test.tsx
> +        },
Цей мок і мок нижче в наступному `test` - вони ж однакові по суті і їх можна винести в beforeEach.

2023-05-16 11:01 UTC, v4voloshyn commented on src/pages/main-page/MainPage.test.tsx
> +    );
Теж можна винести в beforeEach

2023-05-16 11:01 UTC, v4voloshyn commented on src/pages/main-page/MainPage.test.tsx
> +    );
Теж можна винести в beforeEach